model: clip
task: classification
subtask: feature-extraction
countries:
  - CH
img_height: 224
img_width: 224
preprocessor: clip
targets:
  - region
lr: 0.001
optimizer: adam
loss: ce
epochs: 200
metrics:
  - acc
dense-1: 64
dropout_dense: 0.5