model: clip
task: regression
subtask: feature-extraction
countries:
  - CH
img_height: 224
img_width: 224
preprocessor: clip
targets:
  - latitude
  - longitude
lr: 0.0002
optimizer: adam
loss: mse
epochs: 200
metrics:
  - mse
  - mae
group_norm: 4
dense-1: 64
dropout_dense: 0.5