model: clip
clip_str: clip_vit_large_patch14_336
task: regression
subtask: feature-extraction
countries:
  - CH
img_height: 336
img_width: 336
preprocessor: clip
targets:
  - latitude
  - longitude
lr: 0.0002
optimizer: adam
loss: mse
epochs: 200
metrics:
  - mse
  - mae
group_norm: 4
dense-1: 64
dropout_dense: 0.5