model: sota_cnn_net
model_name: mobile_net_v2
task: classification
subtask: from-scratch # fine-tuning, feature-extraction, from-scratch
countries:
  - IT
img_height: 224
img_width: 224
preprocessor: mobile_net_v2
targets:
  - region
lr: 0.001
optimizer: adam
loss: ce
epochs: 100
metrics:
  - acc
dropout_dense: 0.4