model: naive_reg_net
img_height: 200
img_width: 200
targets:
  - latitude
  - longitude
lr: 0.001
optimizer: adam
loss: mse
epochs: 50
metrics:
  - mse
  - mae
num_blocks: 3
block_size: 2
filters: 64
maxpool: 2
averpool: 2
dense-1: 200
dropout_conv: 0.4
dropout_dense: 0.5